[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "on"
shape = "Beam"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
blur = true
option_as_alt = "Both"

[window.padding]
x = 20
y = 20

[window.dimensions]
columns = 60
lines = 20

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[colors.primary]
background = "#1A1B26"
foreground = "#C0CAF5"

[colors.normal]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#A9B1D6"

[colors.bright]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"
